/**
 * AI Program Customization Screen - STARTER VERSION
 *
 * Allows editing AI-generated program before enrollment:
 * - View generated program details
 * - Swap exercises (browse library)
 * - Adjust sets/reps/rest
 * - Reorder workouts
 * - Save customized program
 *
 * TODO: Full implementation with drag-drop, exercise picker, etc.
 */

import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
} from 'react-native';
import { Stack, useRouter, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useStyledTheme } from '@theme/ThemeProvider';

export default function AICustomizeScreen() {
  const theme = useStyledTheme();
  const router = useRouter();
  const params = useLocalSearchParams();

  // TODO: Load AI-generated program from params
  const [programName, setProgramName] = useState('Custom AI Program');
  const [workouts, setWorkouts] = useState<any[]>([]);

  const textColors = {
    primary: theme.isDark ? theme.colors.dark.text.primary : theme.colors.light.text.primary,
    secondary: theme.isDark ? theme.colors.dark.text.secondary : theme.colors.light.text.secondary,
  };

  const bgColors = {
    primary: theme.isDark ? theme.colors.dark.bg : theme.colors.light.bg,
    card: theme.isDark ? theme.colors.dark.card : theme.colors.light.card,
  };

  const handleSave = () => {
    Alert.alert('Success', 'Program customized and saved!', [
      { text: 'OK', onPress: () => router.replace('/(tabs)/workouts') },
    ]);
  };

  return (
    <View style={[styles.container, { backgroundColor: bgColors.primary }]}>
      <Stack.Screen
        options={{
          title: 'Customize Program',
          headerShown: true,
          headerStyle: { backgroundColor: bgColors.primary },
          headerTintColor: textColors.primary,
        }}
      />

      <ScrollView style={styles.scrollView} contentContainerStyle={styles.content}>
        {/* Info Card */}
        <View style={[styles.infoCard, { backgroundColor: theme.colors.primary[100] }]}>
          <Ionicons name="information-circle" size={24} color={theme.colors.primary[600]} />
          <Text style={[styles.infoText, { color: theme.colors.primary[700] }]}>
            This is a starter template. Full customization features coming soon:
            {'\n'}• Swap exercises{'\n'}• Adjust sets/reps/rest{'\n'}• Reorder workouts{'\n'}•
            Drag-drop interface
          </Text>
        </View>

        {/* Program Preview */}
        <View style={[styles.section, { backgroundColor: bgColors.card }]}>
          <Text style={[styles.sectionTitle, { color: textColors.primary }]}>Program Overview</Text>
          <Text style={[styles.programName, { color: textColors.primary }]}>{programName}</Text>
          <Text style={[styles.programMeta, { color: textColors.secondary }]}>
            Generated by AI • 12 weeks • 36 workouts
          </Text>
        </View>

        {/* Placeholder: Workouts List */}
        <View style={[styles.section, { backgroundColor: bgColors.card }]}>
          <Text style={[styles.sectionTitle, { color: textColors.primary }]}>Workouts</Text>
          <Text style={[styles.placeholderText, { color: textColors.secondary }]}>
            Workout list with edit options will appear here.{'\n\n'}Each workout can be customized
            with exercise picker, sets/reps adjuster, and reordering.
          </Text>
        </View>

        {/* Save Button */}
        <TouchableOpacity
          onPress={handleSave}
          style={[styles.saveButton, { backgroundColor: theme.colors.primary[500] }]}
        >
          <Ionicons name="checkmark-circle" size={24} color="#FFFFFF" />
          <Text style={styles.saveButtonText}>Save & Enroll in Program</Text>
        </TouchableOpacity>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollView: { flex: 1 },
  content: { padding: 20, paddingBottom: 40 },
  infoCard: {
    flexDirection: 'row',
    gap: 12,
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
  },
  infoText: { flex: 1, fontSize: 14, lineHeight: 20 },
  section: {
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  programName: { fontSize: 24, fontWeight: '800', marginBottom: 8 },
  programMeta: { fontSize: 14 },
  placeholderText: { fontSize: 15, lineHeight: 22 },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    padding: 18,
    borderRadius: 12,
    marginTop: 12,
  },
  saveButtonText: { fontSize: 18, fontWeight: '700', color: '#FFFFFF' },
});
